"""BDD contract tests for the native OpenClaw lifecycle controller package."""

from __future__ import annotations

import json
from pathlib import Path

PLUGIN = Path(__file__).parents[1] / "integrations" / "openclaw-lifecycle-plugin"
DISPATCHER = Path(__file__).parents[1] / "scripts" / "dispatch_codex_pr_review.py"


def test_given_a_native_plugin_when_packaged_then_manifest_and_runtime_entry_agree() -> None:
    package = json.loads((PLUGIN / "package.json").read_text(encoding="utf-8"))
    manifest = json.loads((PLUGIN / "openclaw.plugin.json").read_text(encoding="utf-8"))

    assert manifest["id"] == "collatz-lifecycle"
    assert package["openclaw"]["extensions"] == ["./index.js"]
    # OpenClaw 2026.7.1-2 validates during `plugins install`; requiring these
    # values makes a fresh installation impossible to configure through its CLI.
    assert "required" not in manifest["configSchema"]


def test_given_an_openclaw_turn_when_the_controller_loads_then_all_receipt_hooks_exist() -> None:
    source = (PLUGIN / "index.js").read_text(encoding="utf-8")

    for hook in ("before_agent_run", "before_tool_call", "after_tool_call", "agent_end"):
        assert f'api.on("{hook}"' in source
    assert '"begin-operation"' in source
    assert '"finish-operation"' in source
    assert '"consume"' in source


def test_successful_pr_create_or_update_emits_a_durable_review_handoff() -> None:
    source = (PLUGIN / "index.js").read_text(encoding="utf-8")

    assert '"request-review"' in source
    assert "isPullRequestMutation" in source
    assert "reviewRequestFrom" in source
    assert "reviewRequests.set" in source
    assert "dispatchReview(config)" in source
    assert "reviewDispatcherCommand" in (PLUGIN / "openclaw.plugin.json").read_text(encoding="utf-8")


def test_review_dispatcher_claims_then_records_a_structured_terra_receipt() -> None:
    source = DISPATCHER.read_text(encoding="utf-8")

    assert '"claim-review"' in source
    assert '"record-review"' in source
    assert '"openai/gpt-5.6-terra"' in source
    assert "Generated by independent OpenClaw Codex review" in source
    assert "must not edit source, push, resolve threads, or" in source
    assert "merge. Do not review a different SHA." in source


def test_given_a_typed_hook_when_it_needs_plugin_settings_then_it_reads_event_context() -> None:
    source = (PLUGIN / "index.js").read_text(encoding="utf-8")

    assert "event?.context?.pluginConfig" in source
    assert "const config = context.pluginConfig;" not in source


def test_given_a_terminal_hook_when_lifecycle_observation_fails_then_it_reports_and_cleans_up() -> (
    None
):
    source = (PLUGIN / "index.js").read_text(encoding="utf-8")

    assert 'report("after_tool_call", error);' in source
    assert 'report("agent_end", error);' in source


def test_canonical_checkout_requires_external_state_and_observation_mode() -> None:
    manifest = json.loads((PLUGIN / "openclaw.plugin.json").read_text(encoding="utf-8"))

    properties = manifest["configSchema"]["properties"]
    assert properties["enforcementMode"]["default"] == "observe"
    assert properties["receiptToolNames"]["default"] == []
    assert "repoPath" in properties
    assert "stateDir" in properties


def test_fresh_install_bootstrap_is_valid() -> None:
    manifest = json.loads((PLUGIN / "openclaw.plugin.json").read_text(encoding="utf-8"))
    source = (PLUGIN / "index.js").read_text(encoding="utf-8")
    readme = (PLUGIN / "README.md").read_text(encoding="utf-8")

    assert "required" not in manifest["configSchema"]
    assert "repoPath, stateDir, and scripts/agent_lifecycle.py are required" in source
    assert "2026.7.1-2" in readme
