#!/usr/bin/env python3
"""Claim one durable PR-review handoff, run Terra, and record its receipt.

This program is a trusted host-side adapter. It receives no PR-derived command
arguments: all review identity comes from the lifecycle ledger after an atomic
claim. It deliberately delegates GitHub review posting to the isolated agent's
available GitHub tool connection.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any


def _run_json(command: list[str]) -> dict[str, Any]:
    result = subprocess.run(command, capture_output=True, text=True, check=False)
    if result.returncode:
        raise RuntimeError(result.stderr.strip() or "command failed")
    return json.loads(result.stdout)


def _prompt(review_key: str, review: dict[str, Any]) -> str:
    return f"""You are an independent, review-only PR reviewer.

Review repository {review['repository']} PR #{review['pr_number']} at exact
head SHA {review['head_sha']} for review round {review['round']}.

You may read the PR, diff, CI evidence, and existing review threads. You may
post a GitHub review, but you must not edit source, push, resolve threads, or
merge. Do not review a different SHA.

Return ONLY one JSON object with this exact schema:
{{
  "repository": "{review['repository']}",
  "pr_number": {review['pr_number']},
  "head_sha": "{review['head_sha']}",
  "round": {review['round']},
  "model": "openai/gpt-5.6-terra",
  "verdict": "approved|changes_requested|escalated",
  "review_url": "https://... or null",
  "findings": [{{"severity":"P0|P1|P2|architecture", "summary":"...", "url":"https://... or null"}}]
}}

The GitHub review body, if posted, must begin exactly:
Generated by independent OpenClaw Codex review

Durable review key: {review_key}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-path", required=True)
    parser.add_argument("--state-dir", required=True)
    parser.add_argument("--python-command", default="python3")
    parser.add_argument("--dispatcher", default="terra-reviewer")
    parser.add_argument("--review-key")
    args = parser.parse_args()

    lifecycle = Path(args.repo_path) / "scripts" / "agent_lifecycle.py"
    base = [args.python_command, str(lifecycle), "--repo-path", args.repo_path, "--state-dir", args.state_dir]
    claimed = _run_json(base + ["claim-review", "--dispatcher", args.dispatcher] + (["--review-key", args.review_key] if args.review_key else []))
    if claimed["decision"] == "none_pending":
        return 0
    if claimed["decision"] != "claimed":
        raise RuntimeError(f"unexpected claim decision: {claimed['decision']}")

    review_key = str(claimed["review_key"])
    review = claimed["review"]
    agent = subprocess.run(
        [
            "openclaw", "agent", "exec", "--json", "--cwd", args.repo_path,
            "--model", "openai/gpt-5.6-terra", "--timeout", "600", _prompt(review_key, review),
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if agent.returncode:
        raise RuntimeError(agent.stderr.strip() or "Terra reviewer failed")
    envelope = json.loads(agent.stdout)
    raw = envelope.get("text") or envelope.get("result") or envelope.get("output")
    if not isinstance(raw, str):
        raise RuntimeError("Terra reviewer returned no text receipt")
    receipt = json.loads(raw)
    _run_json(base + ["record-review", "--review-key", review_key, "--receipt-json", json.dumps(receipt)])
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, RuntimeError, json.JSONDecodeError, KeyError, TypeError) as exc:
        print(f"codex PR review dispatch failed: {exc}", file=sys.stderr)
        raise SystemExit(2)
